[workspace]
authors = ["emptist <jigme1968@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025122205,<0.27"
